on:
  push:
    branches:
      - master








jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "login to docker hub"
        run: docker login -u ${{ secrets.USER }} -p ${{ secrets.TOKEN }}
      - name: "bulding docker image"
        run: docker build -t ${{ secrets.USER }}/nourimage .
      - name: "pushing docker image"
        run: docker push ${{ secrets.USER}}/nourimage
